name: "Build and publish package"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    # - uses: ryanccn/attic-action@v0.3.1
    #   with:
    #     endpoint: ${{ secrets.ATTIC_ENDPOINT }}
    #     cache: ${{ secrets.ATTIC_CACHE }}
    #     token: ${{ secrets.ATTIC_TOKEN }}
    - run: nix run .#ci
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
